[build]
  command = "npm run build"
  publish = "dist"

# Ensure SPA routing works on refresh for client-side routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"

# During local dev with `netlify dev`, proxy functions and vite server
[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200
